# Generated by Django 4.0 on 2021-12-31 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_zip_userprofile_zip_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='zip_number',
        ),
    ]
