# Generated by Django 4.0 on 2022-01-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='review',
            field=models.TextField(default=''),
        ),
    ]
